debug: true
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
#    url: jdbc:postgresql://localhost:5432/school_book
    url: postgres://ivastdlacjjmgr:c62fb8e39d5aba58a808731331cacb5cf1407cb96ac564ba8f9a51ccaeb3ba8e@ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/d52jpfhsrgroq0

    #    password: 911368169umid
    password: c62fb8e39d5aba58a808731331cacb5cf1407cb96ac564ba8f9a51ccaeb3ba8e
#    username: postgres
    username: ivastdlacjjmgr
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 100MB
jwt:
  key: 132ea09c203531f15e3d055a4e305eda
  expire: 86400000
server:
  port: 3054
springdoc:
  swagger-ui:
    path: /apidoc